all:
	g++ -o serverA serverA.cpp -lsocket -lnsl -lresolv
	g++ -o serverB serverB.cpp -lsocket -lnsl -lresolv
	g++ -o serverC serverC.cpp -lsocket -lnsl -lresolv
	g++ -o aws aws.cpp -lsocket -lnsl -lresolv
	g++ -o client client.cpp -lsocket -lnsl -lresolv 


serverA: 
	./serverA

serverB: 
	./serverB

serverC: 
	./serverC

aws: 
	./aws

clean:
	rm -rf serverA
	rm -rf serverB
	rm -rf serverC
	rm -rf aws
	rm -rf client
